### ISSUE TITLE
Stripchat is making a lot of videoclips

### ISSUE THREAD

**Issue by xAstroBoy** [lossless1024/StreaMonitor#135]
The videos download, but even with the newest ffmpeg it still makes a ton of mini video files, is annoying!

**Comment by DerBunteBall** [comment]
This is a limitation of ffmpeg.

I took a look on it and I guess SC uses the LL Extension of HLS published by Apple in 2019.

The problem with this seems - as far as I could find out and understood it correctly - that segments getting invalidated really fast. The stuff is made to be really real-time streaming. That leads ffmpeg to simply stop by default because of this. I guess because it thinks the stream is ended or has stopped when it sees to much invalidated segments. I couldn't find an option to give ffmpeg a tolerance for finally lost segments.

It seems that ```-re```  helps a bit. But this option is meant for other stuff. And it leads to total segment drops when a segment is finally invalidated.

I could get the best results with this option on a 1GBit connection which was only used for capturing. So you need this to capture SC:

1. A dedicated caputring system on big internet connection with low latency
2. Most recent ffmpeg
3. The above option.

Then you can capture an hour or so but also from time to time ffmpeg will stop and needs to be respawned.
