### ISSUE TITLE
List Index out Of Range Error

### ISSUE THREAD

**Issue by MoeBile** [lossless1024/StreaMonitor#138]
Tried to stat up the downloadr and got this error:

\StreaMonitor-master>python Controller.py
Traceback (most recent call last):
  File "C:\Users\Donald\Documents\StreaMonitor-master\Controller.py", line 5, in <module>
    if sys.argv[1].startswith("-h"):
       ~~~~~~~~^^^
IndexError: list index out of range

That was on Arch, it had worked a few days ago. Tried to it get it working on Windows and got the same error.

**Comment by DerBunteBall** [comment]
You have called Controller.py without any parameters. The IndexError then always occurs because no exception handling is implemented.

sys.argv simply does not contain an index 1 when called without any parameters, but only the index 0 with Controller.py as the value.

To start the downloader, call Downloader.py in a suitable Python environment. Then you end up in the CLI or can control the downloader via Controller.py.

**Comment by MoeBile** [comment]
OK, got it working thanks.

**Comment by MoeBile** [comment]
OK, got it working. Thanks.
