### ISSUE TITLE
help it cant work

### ISSUE THREAD

**Issue by guoxintouzi** [lossless1024/StreaMonitor#139]
![屏幕截图 2024-03-24 210149](https://github.com/lossless1024/StreaMonitor/assets/132179920/76091d93-1ac2-47dc-90a1-00cbfcabe206)  how to solve it

**Comment by DerBunteBall** [comment]
I cannot reproduce the problem under macOS.

Are all dependencies installed correctly in the Python environment?

If everything is running in the browser, there should be no network problem.

Note: StripChat produces strange results on slow lines with latency issues probably due to the real-time extensions of HLS.

<img width="565" alt="Bildschirmfoto 2024-03-24 um 17 19 30" src="https://github.com/lossless1024/StreaMonitor/assets/33455788/a8bd513b-4bab-4944-8c36-5a998e209876">

**Comment by guoxintouzi** [comment]
It seems that feedback has improved somewhat, with the issues being more focused now.  why?
![Uploading 微信截图_20240325185142.png…]()

**Comment by guoxintouzi** [comment]
It seems that feedback has improved somewhat, with the issues being more focused now. why?

![20240325185142](https://github.com/lossless1024/StreaMonitor/assets/132179920/466e6dd1-55c4-40de-9d1b-251d233a8226)

**Comment by guoxintouzi** [comment]
there are some new problems ,as it ,help me 
![20240325212706](https://github.com/lossless1024/StreaMonitor/assets/132179920/e0f826b9-7a9b-45d2-89bb-337464b4ecb8)

**Comment by guoxintouzi** [comment]
thank you ,i have solve it ,the adhome caused it,and i rebuild all dependencies  in virtualenv ,then it work properly
