### ISSUE TITLE
Start/Stop all and Selected Recordings

### ISSUE THREAD

**Issue by Odogwu3000** [lossless1024/StreaMonitor#22]
Possibility to Stop/Start all/selected recordings

**Comment by agocsdaniel** [comment]
Planned

**Comment by lossless1024** [comment]
I thought about this already and is partly done

**Comment by lossless1024** [comment]
But i think only the start/stop all can be implemented nicely, because there is a chance that you have streamers with the same name on different sites. The other solution is to separate streamers with commas or something, but I don't like that approach.

**Comment by DerBunteBall** [comment]
Wouldn't it help to assign streamers/jobs something like a uuid? This makes it easier to have same names on different sites or VR and normal streams.

How the stuff could be handled on the command line is another thing.

**Comment by lossless1024** [comment]
It wouldn't really, because I think you might not want to copy&paste id-s or find numbers yourself to start/stop/etc a streamer. This means you will use username. If there would be a collision, you have to specify site too. Or at least I think that this is a proper way. 
So the program actually have to search the list of streamers for the username and site. Of course this could be smarter, as everything, but currently I don't have so much time for this. However I wanted to migrate the command line to use the cmd library, but that is another story and doesn't help us here. (A history and auto-completion feature also would be great)

**Comment by DerBunteBall** [comment]
Hm.... yes it would have the most effect to the internal logic.

So the Controller could be generally made more userfriendly (in sense of a well defined CLI app). 

That would be easy for GUI software hm.... to have it in the CLI of the Downloader would be really a problem. So it couldn't be nearly impossible to do this nicely. My only thought would be to make CLI GUI with (n)curses.

**Comment by lossless1024** [comment]
Also you can check the `start *` and `stop *`

**Comment by DerBunteBall** [comment]
The concept you have designed it for is my usecase. So a GUI could be also a remote GUI that's the nice thing at this design. I would keep the Downlaoder as thin as possible.

I think my Python skills are saidly to bad to do patches.

**Comment by lossless1024** [comment]
A remote GUI would be a good idea. Also it can be easily done with ZMQ using a JSON based protocol.

**Comment by DerBunteBall** [comment]
Exactly this. So the protocol would need a bit of "specification" so it would be possible to have GUIs, TUIs or WebUIs like wanted.

A bit of authentication possibilities or so and a GUI could be used for mutli host managment.

Also it can be used locally so it's not important whether the server runs local or remote.
