### ISSUE TITLE
Set resolution

### ISSUE THREAD

**Issue by maddi4u** [lossless1024/StreaMonitor#23]
How to set custom resolution to record streams in 720p or 480p or 1080p

**Comment by DerBunteBall** [comment]
Actually not possible. It's statically in bot.py (should decide the best available) and the Downloader actually not supports general options.

Eventually @lossless1024 sets this to TODO List.

Best Regards

**Comment by lossless1024** [comment]
It is possible I think, however there are sites where there is only one resolution.

**Comment by maddi4u** [comment]
Okay
Was asking because it took a lot of space

**Comment by ThEnGI** [comment]
> Actually not possible. It's statically in bot.py (should decide the best available) and the Downloader actually not supports general options.

Wanting to use only one resolution, which line should I change?. eg. 720p streams only

**Comment by ThEnGI** [comment]
more help?
I'm not good at python, I tried changing the "position" parameter no effect
is something easy or do I have to redo the whole function?

Thanks in advance
T

**Comment by DerBunteBall** [comment]
It's not that simple to change it.

The easiest but really dirty solution is the following:

You could install the m3u8 extension ```pip3 install m3u8``` in your virtual environment and try my crappy reimplementation of the function:

```python
def getBestSubPlaylist(url, position):
    try:
        wanted_resolution = "1280x720"
        sources = {}
        result = requests.get(url)
        m3u8_doc = result.content.decode("utf-8")
        variant_m3u8 = m3u8.loads(m3u8_doc)
        if variant_m3u8.is_variant:
            for playlist in variant_m3u8.playlists:
                sources[str(playlist.stream_info.resolution[0])+"x"+str(playlist.stream_info.resolution[1])] = playlist.uri
            if sources[wanted_resolution].startswith("https://"):
                return sources[wanted_resolution]
            else:
                return '/'.join(url.split('.m3u8')[0].split('/')[:-1]) + '/' + sources[wanted_resolution]
        else:
            return None
    except:
        return None
```

This should return the 720p chunklist URL. You could wrap this in a little script to test it. ```wanted_source``` follows the resolution format ```width x height``` so 1080p would be ```1920x1080```. Keep in mind that the script doesn't check whether the set resolution exists. A non existing one should give a None back because it throws an exception. Also import m3u8 like this: 

```python
import m3u8
```

Just a dirty hack and not tested in StreaMonitor source. Use at own risk. URL loading of m3u8 seems to be really unhappy with much stuff so I had only working results by converting to string in a prior step and throw it in as a string.

Best Regards

**Comment by ThEnGI** [comment]
Thanks for the dedicated time!
I tried it on CB with 720p and 480p resolution, it seems to do the opposite of what you said: there are too many streams and it can't choose......
joking aside, from a first search it seems that there is a problem with the variable "position" which is passed more then one time

Anyway this error: 
```
ERROR - [CB] alison_lu: getBestSubPlaylist() got multiple values for argument 'position'
Traceback (most recent call last):
     File "/home/XXX/StreaMonitor/streamonitor/bot.py", line 123, in run
         self.getVideo(self, self.getVideoUrl(), self.genOutFilename())
     File "/home/XXX/StreaMonitor/streamonitor/sites/chaturbate.py", line 15, in getVideoUrl 
         return self.getBestSubPlaylist(self.lastInfo['url'], position=-1)
TypeError: getBestSubPlaylist() got multiple values for argument 'position'
```
Could the error be in the _getBestSubPlaylist_ function call on line 14 of the chaturbate.py file? in which "position" is set to -1

Sorry I'm not too helpful :-(

You are very quick to answer, know that I am in no hurry! 
Thanks again

**Comment by DerBunteBall** [comment]
Tested in StreaMonitor code with a CB model.

Actually it's not possible to declare different resolutions for models. So you need to decide which you want. If you set ```wanted_resolution``` to 1280x720 you will always get 720p for all extractors who call this function. The position argument is simply ignored.

Check this gist (https://gist.github.com/DerBunteBall/3b8c65c39c543312716c2d036ef4b2fa) to see how the file should look. Gives 720p files when adding and starting a CB model.

You need to set the resolution in the class method so it's not configurable by a file or so. It's really dirty.

Short note: ffmpeg Downlaoder thorws a funny exception but starts ffmpeg on Python 3.11. Seems that something has changed in Popen. Don't investigated it for now.

**Comment by ThEnGI** [comment]
> Actually it's not possible to declare different resolutions for models. 

I figured it was one resolution for all streams! which is just what I was looking for
Dirty or not is perfect, I don't know why but copy and paste doesn't work, from git it works.

With a view to improvement: Isn't it possible to write it so that if the requested resolution (eg 1080p) is not available, does the function look for the best resolution? in this case you would have two functions if the result of the first is null you start the second. So you can add it to the program without impacting its original functionality.

Again abusing your kindness, is it possible to write a script that returns the available resolutions?

Thank you so much !!!

**Comment by ThEnGI** [comment]
Thanks,[DerBunteBall](https://github.com/DerBunteBall) youtube-dl is enough.
Now is working with about 30 cams: CB/CAM4/MFC/StripChat/StreaMate. 15 active in 480p
So far no errors on screen, time for a WE endurance test 

Have a great weekend

**Comment by lossless1024** [comment]
I added it. Check it if you have issues, but I tested all sites and it seems to work properly

**Comment by maddi4u** [comment]
Great work.

**Comment by NikitaBeloglazov** [comment]
Please write about quality choice in the README. Without mentioning in the readme, this function seems to be hidden from prying eyes 👀
There is a table of qualities, but there is no how to choose quality:)
