### ISSUE TITLE
Rate Limited

### ISSUE THREAD

**Issue by mK33y** [lossless1024/StreaMonitor#3]
so i added about 80 models and when i stopped the script it said "rate limited" on every model. where is the problem? my hardware is more then enough to run even 1000 at the same time even my network is strong enough (1gb up and down).

**Comment by lossless1024** [comment]
Chaturbate rate limits the status queries per client. 80 models are slightly too much (because it is not a normal situation) and the query interval is too short, so the site will rate limit you. Add less models or use more IP addresses

**Comment by DerBunteBall** [comment]
Did this start after a time or directly after startup?

In general a rate limit leads to a rerequest every 3 minutes. The problem is that simultanous requests (unimportant which size they have) is unnormal and indicates scraping and other stuff. Also the website doesn't behave like that.

So it would be only fixable by changing the code so that the rerequest intervals getting modified slightly by e.g. randomize them in time ranges.

**Comment by sminato27** [comment]
It happens directly after startup. Still happening on the last version released.
