### ISSUE TITLE
Private Show

### ISSUE THREAD

**Issue by sminato27** [lossless1024/StreaMonitor#9]
There's any way to "bypass" private show from CB and record it?

**Comment by lossless1024** [comment]
Sorry, that isn't possible. Private shows are really private. The only possible solution is to implement a feature to allow using site credentials and automatically record shows when you are in private.
I didn't implement this before, because I think when you are in private, you usually have interactions with the model and this tool is made for recording streams even when you are away. There is a browser plugin called Video DownloadHelper, which is usually able to record these kind of shows.

**Comment by sminato27** [comment]
I'll never pay for private shows only for record it but thanks for the explaining.

**Comment by eldepor** [comment]
What if a streamer sets a public password and I want to record it?
